_extends: .github

repository:
  name: kube-score-pre-commit-hook
  description: kube score pre-commit hook
  homepage: https://github.com/bjd2385/kube-score-pre-commit-hook

  # A comma-separated list of topics to set on the repository
  topics: Helm, Kubernetes, pre-commit, kube-score
  private: false
